name: tailor_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  cupertino_stepper: ^0.2.1
  easy_stepper: ^0.8.3
  emoji_keyboard_flutter: ^1.3.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9 
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.0
  flutter_native_splash: ^2.3.6
  flutter_svg: ^2.0.9
  # geocoding: ^2.1.1
  google_mobile_ads: ^4.0.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.6
  hidden_drawer_menu: ^3.0.1
  http: ^1.1.2
  image_picker: ^1.0.5
  intl_phone_number_input: ^0.7.4
  line_icons: ^2.0.3
  # location: ^5.0.3
  lottie: ^2.7.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  shimmer: ^3.0.0
# permission_handler: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
   -  assets/
   -  assets/1/

flutter_icons:
  image_path: "assets/app-logo.jpeg" 
  android: true